### ISSUE TITLE
Initial Release

### ISSUE THREAD

**Issue by plribeiro3000** [fog/fog-tutum#1]
Hey @bfosberry !

I finished migrating the code from you pull request to the gem.
The shindo tests are not working (i can explain it further if you want) but i would recommend you to migrate them to minitest.

A simple todo list for you:
- [x] Configure `fog-tutum.gemspec` with your data (I couldn't find you email and name)
- [ ] Configure travis support (All the required files are already configured in the repo :smile:)
- [ ] Fix the tests (or migrate to minitest :+1:)
- [ ] Keep doing the good work. =)
- [ ] Add `fog-tutum` as a runtime_dependency to `fog`

Let me know if want/need insight on anything.

**Comment by plribeiro3000** [comment]
cc/ @geemus

**Comment by geemus** [comment]
Thanks!

**Comment by bfosberry** [comment]
I'll have some time to work on this shortly. 

Also someone made a dedicated ruby client: https://github.com/tutumcloud/ruby-tutum, so I'll be converting over to that. There are also a number of new features around node creation, and backend integration I'll need to work in. I'll try and get this done over christmas break.

Thanks for all the help with this!

**Comment by geemus** [comment]
@bfosberry sounds good, just let us know if you have any questions or things we can help with. Thanks!

**Comment by bfosberry** [comment]
How can I test this lib in isolation via irb? I can run irb, create a Fog::Tutum::Compute::Real class correctly, but how can I create models and test those via the console?

 Also is there an example of a lib set up with minitest I can reference?

**Comment by plribeiro3000** [comment]
@bfosberry You should be able to load any model you reference in the Compute class using the methods `model` and `collection`. Example: In [this line](https://github.com/fog/fog-xenserver/blob/master/lib/fog/compute/xen_server.rb#L18) the collection `blobs` was defined using the method `collection`. Because of that i will be able to call `blobs` in the connection object.

In `fog-tutum` you have [this collection](https://github.com/fog/fog-tutum/blob/master/lib/fog/compute.rb#L11) defined and because of that you should be able to call `servers` in the `Fog::Tutum::Compute::Real` class you initialized.

For minitest support you should take a look at [`fog-xenserver`](https://github.com/fog/fog-xenserver). It is using minitest for all tests and has a good code coverage.

Let me know if you have more questions.

**Comment by bfosberry** [comment]
Hmm, that's what I thought, regarding the models and collections, but it's not working for me:

```
2.1.2 :006 > fs.container
NoMethodError: undefined method `container' for #<Fog::Compute::TutumService::Real:0x00000003c640c8>
    from (irb):6
    from /home/bfosberry/.rvm/rubies/ruby-2.1.2/bin/irb:11:in `<main>'
2.1.2 :007 > fs.containers
NoMethodError: undefined method `containers' for #<Fog::Compute::TutumService::Real:0x00000003c640c8>
    from (irb):7
    from /home/bfosberry/.rvm/rubies/ruby-2.1.2/bin/irb:11:in `<main>'

```

container.rb is server.rb with a few changes, same with containers.rb

I tried adding an autoload models section, I wonder if its related to the package structure, i.e. fog/tutum_service/models/compute vs fog/compute/tutum_service/models

my compute.rb looks like this atm:

```
module Fog
  module Compute
    class TutumService < Fog::Service
      autoload :Models, 'fog/tutum_service/models/compute'
      requires   :tutum_username, :tutum_api_key
      model_path 'fog/tutum_service/models/compute'

      model      :container
      collection :containers

      .....

end
```

The model path is correct. Containers is defined within Fog::Compute::TutumService as is Container.

**Comment by bfosberry** [comment]
It think it may be an fog core import issue, from IRB:

```
2.1.2 :014 > fs.containers
NoMethodError: undefined method `containers' for #<Fog::Compute::TutumService::Real:0x00000003ff4a30>
    from (irb):14
    from /home/bfosberry/.rvm/rubies/ruby-2.1.2/bin/irb:11:in `<main>'
2.1.2 :015 > fs.model :container
NoMethodError: undefined method `model' for #<Fog::Compute::TutumService::Real:0x00000003ff4a30>
    from (irb):15
    from /home/bfosberry/.rvm/rubies/ruby-2.1.2/bin/irb:11:in `<main>'
```

and

```
2.1.2 :001 > Fog
 => Fog 
2.1.2 :002 > Fog::
                                 Fog::hash                        Fog::protected_instance_methods
Fog::TutumService                Fog::include                     Fog::protected_method_defined?
Fog::__id__                      Fog::include?                    Fog::protected_methods
Fog::__send__                    Fog::included_modules            Fog::public_class_method
Fog::ancestors                   Fog::inspect                     Fog::public_constant
Fog::autoload                    Fog::instance_eval               Fog::public_instance_method
Fog::autoload?                   Fog::instance_exec               Fog::public_instance_methods
Fog::class                       Fog::instance_method             Fog::public_method
Fog::class_eval                  Fog::instance_methods            Fog::public_method_defined?
Fog::class_exec                  Fog::instance_of?                Fog::public_methods
Fog::class_variable_defined?     Fog::instance_variable_defined?  Fog::public_send
Fog::class_variable_get          Fog::instance_variable_get       Fog::remove_class_variable
Fog::class_variable_set          Fog::instance_variable_set       Fog::remove_instance_variable
Fog::class_variables             Fog::instance_variables          Fog::respond_to?
Fog::clone                       Fog::is_a?                       Fog::send
Fog::const_defined?              Fog::kind_of?                    Fog::singleton_class
Fog::const_get                   Fog::method                      Fog::singleton_class?
Fog::const_missing               Fog::method_defined?             Fog::singleton_method
Fog::const_set                   Fog::methods                     Fog::singleton_methods
Fog::constants                   Fog::module_eval                 Fog::taint
Fog::define_singleton_method     Fog::module_exec                 Fog::tainted?
Fog::display                     Fog::name                        Fog::tap
Fog::dup                         Fog::nil?                        Fog::to_enum
Fog::enum_for                    Fog::object_id                   Fog::to_s
Fog::eql?                        Fog::prepend                     Fog::trust
Fog::equal?                      Fog::private_class_method        Fog::untaint
Fog::extend                      Fog::private_constant            Fog::untrust
Fog::freeze                      Fog::private_instance_methods    Fog::untrusted?
Fog::frozen?                     Fog::private_method_defined?     
Fog::gem                         Fog::private_methods           
```

**Comment by geemus** [comment]
Hmm, with this:

```
      model_path 'fog/tutum_service/models/compute'

      model      :container
      collection :containers
```

I would expect to to be fine as long as those are defined in `fog/tutum_service/models/compute/container.rb` and `fog/tutum_service/models/compute/containers.rb` respectively. The autoload shouldn't be needed (the model_path/model/collection stuff will do the same thing for all intents and purposes).

**Comment by plribeiro3000** [comment]
@bfosberry Maybe if you pull your code to some branch we can give a better feedback.

**Comment by bfosberry** [comment]
I think that's best, I'll have to put this down for a while and come back to it though. thanks guys

**Comment by plribeiro3000** [comment]
:+1:

**Comment by geemus** [comment]
No problem, just let us know if we can help should you find time to pick it back up. Thanks!
